apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing-backend
  template:
    metadata:
      labels:
        app: billing-backend
    spec:
      containers:
        - name: backend
          image: caduunisal/billing-backend:v1
          ports:
            - containerPort: 5000
